### ISSUE TITLE
存储本地副本的问题

### ISSUE THREAD

**Issue by csrgxtu** [csrgxtu/Sauron#2]
像谷歌爬虫一样，每个URL都对应着一个本地副本，至于这个副本暂时有什么用，我也不确定，先存储起来吧。

**Comment by Digital2Slave** [comment]
okay.

**Comment by csrgxtu** [comment]
粗略计算了一下，光是豆瓣的266w的本地副本就需要246G的硬盘，所以技术总监建议使用七牛云存储了。代码已经改成了七牛了。
