### ISSUE TITLE
20/Nov/2015 要做的事情

### ISSUE THREAD

**Issue by csrgxtu** [csrgxtu/Sauron#7]
1, slave端减少HTTP请求，每次请求尽量负载更多的数据。
2, master端减少与数据库的链接，优化每次的CRUD操作。Done
3, 丢失URL的处理。
4, Dead URL为插入调试。Done

**Comment by csrgxtu** [comment]
scrapy 的spider执行desructor的方法，因为我们是使用scrapy，所以Python的class的destructor不工作了，但是可以通过signal解决这个问题。
首先，引入包

``` python
from scrapy import signals
from scrapy.xlib.pydispatch import dispatcher
```

其次，在contructor里面添加注册信号

``` python
def __init__(self):
    dispatcher.connect(self.spider_closed, signals.spider_closed)
```

最后，定义spider结束定义函数

``` python
def spider_closed(self, spider):
    logging.info('the destructor emulator here')
```

**Comment by csrgxtu** [comment]
插入Dead URL的问题
之前我们在代码里面做了response.status的检查，但是只能处理2xx和3xx的情况，对于4xx和5xx我们的代码就没有插入到deadurls里面，为什么呢？  
因为scrapy默认的download middleware默认的行为是只把2xx的请求的response返回给你些的代码，但是当遇到4XX或者5XX的时候，你的代码根本就看不到response结果，直接是scrapy报个exception就over了。  
所以若想捕获4xx的请求，只要在你的spider代码中添加如下：

``` python
handle_httpstatus_list = [404] # also 403, 407, 502 etc
```

**Comment by Digital2Slave** [comment]
handle_httpstatus_list = [
400, 401, 402, 403, 404, 405, 406, 407, 408, 409,
410, 411, 412, 413, 414, 415, 416, 417, 418, 419,
420, 421, 422, 423, 424, 426, 428, 429, 431,
440, 444, 449,
450, 451,
494, 495, 496, 496, 497, 498, 499,
500, 501, 502, 503, 504, 505, 506, 507, 508, 509,
510, 511,
520, 522,
598, 599
]
